# Generated by Django 4.2.2 on 2023-07-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='primaryPrice',
            new_name='primary_price',
        ),
    ]
