# Generated by Django 4.2.2 on 2023-08-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='creater',
            new_name='owner',
        ),
    ]
